# Generated by Django 3.0.3 on 2020-04-21 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriberdetails',
            name='due_date',
        ),
    ]
